[package]
name = "monke"
version = "0.0.0-alpha"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parser = {path = "../parser"}
ast = {path = "../ast"}
