name: Dependency Graph

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  setup:
    name: Setup system dependencies
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip-depgraph]')"

    steps:
      - uses: actions/checkout@v2
      - name: Install graphviz
        run: sudo apt install graphviz
      - name: Install cargo-depgraph
        run: cargo install cargo-depgraph
        
  generate:
    name: Generate updated dependency graph
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip-depgraph]')"

    steps:
      - uses: actions/checkout@v2
      - name: Generate dep graph
        run: cargo depgraph --all-deps | dot -Tpng > dependency_graph.png
        
  commit:
    name: Commit & push updated dependency graph
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip-depgraph]')"
    
    steps:
      - uses: actions/checkout@v2
      - uses: EndBug/add-and-commit@vlatest
        with:
          default_author: github_actions
          committer_name: GitHub Actions
          committer_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: "[skip-depgraph] Update dependency graph"
